### ISSUE TITLE
Calling java method from javascript [Question]

### ISSUE THREAD

**Issue by norzak** [jtulach/bck2brwsr#2]
I need to call some static java methods from javascript but I am unable to find a reference or tutorial to accompolish this. As far as I can see from the source code, There is a method name notation, but there isn't a reference explaining that. Is there an easier way to call some java methods from an external javascript code.

**Comment by norzak** [comment]
is this relevant for bck2brwsr?

https://dukescript.com/best/practices/2015/09/15/javacall-syntax.html

**Comment by norzak** [comment]
Looks like we are on our own. Closing this.

**Comment by jtulach** [comment]
Yes, this is relevant. Bck2Brwsr supports HTML/Java API. So all of this
http://bits.netbeans.org/html+java/1.3/net/java/html/js/package-summary.html
will work.

Thanks for trying bck2brwsr.
-jt

Dne 3. 2. 2017 11:41 napsal uživatel "norzak" <notifications@github.com>:

is this relevant for bck2brwsr?

https://dukescript.com/best/practices/2015/09/15/javacall-syntax.html

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jtulach/bck2brwsr/issues/2#issuecomment-277217139>, or mute
the thread

**Comment by norzak** [comment]
Thank you for your reply. The documentation for Bck2Brwsr is very little. Nonetheless, I looked into the bck2brwsr.js, and looks like it is not web worker compatible. It would be great to be able to also run the generated code in a web worker. It is not always about UI.

thanks

**Comment by jtulach** [comment]
The main page is at http://bck2brwsr.apidesign.org/ and it links to http://wiki.apidesign.org/wiki/Bck2BrwsrMangling - that page describes how to call into Bck2Brwsr without using HTML/Java conventions. Doing so isn't as portable as HTML/Java way, but sometimes can be useful too.
